// Coupon helpers shared between the cart and the offerwall page.
// Only a coupon code generated by completing the partner task is valid.

// Prefix for codes generated by the partner-task offerwall
const GENERATED_PREFIX = 'FLASH'

// Generate a unique coupon code (e.g. "FLASH-7K3M2Q")
export function generateCouponCode() {
  const chars = 'ABCDEFGHJKLMNPQRSTUVWXYZ23456789' // no ambiguous chars
  let suffix = ''
  for (let i = 0; i < 6; i++) {
    suffix += chars[Math.floor(Math.random() * chars.length)]
  }
  return `${GENERATED_PREFIX}-${suffix}`
}

// Save the generated coupon code (only set after task completion)
export function setCouponCode(code) {
  try {
    localStorage.setItem('couponCode', code)
  } catch {
    /* ignore */
  }
}

// Get the generated coupon code, or null if none was earned
export function getCouponCode() {
  try {
    return localStorage.getItem('couponCode')
  } catch {
    return null
  }
}

// Whether this entered code matches the earned coupon code
export function isValidCouponCode(entered) {
  const code = getCouponCode()
  if (!code) return false
  return entered.trim().toUpperCase() === code
}
